/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortex

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// PaymentsReadinessAPIService PaymentsReadinessAPI service
type PaymentsReadinessAPIService service

type PaymentsReadinessAPICreateMerchantAccountRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	environment *string
	merchantAccountId *string
	merchantAccountCreateRequest *MerchantAccountCreateRequest
	idempotencyKey *string
}

func (r PaymentsReadinessAPICreateMerchantAccountRequest) Environment(environment string) PaymentsReadinessAPICreateMerchantAccountRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPICreateMerchantAccountRequest) MerchantAccountId(merchantAccountId string) PaymentsReadinessAPICreateMerchantAccountRequest {
	r.merchantAccountId = &merchantAccountId
	return r
}

func (r PaymentsReadinessAPICreateMerchantAccountRequest) MerchantAccountCreateRequest(merchantAccountCreateRequest MerchantAccountCreateRequest) PaymentsReadinessAPICreateMerchantAccountRequest {
	r.merchantAccountCreateRequest = &merchantAccountCreateRequest
	return r
}

// Required for production-safe retries on mutating routes. Reusing a key with a different request body returns 409.
func (r PaymentsReadinessAPICreateMerchantAccountRequest) IdempotencyKey(idempotencyKey string) PaymentsReadinessAPICreateMerchantAccountRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r PaymentsReadinessAPICreateMerchantAccountRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.CreateMerchantAccountExecute(r)
}

/*
CreateMerchantAccount Create a sub-merchant account

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return PaymentsReadinessAPICreateMerchantAccountRequest
*/
func (a *PaymentsReadinessAPIService) CreateMerchantAccount(ctx context.Context) PaymentsReadinessAPICreateMerchantAccountRequest {
	return PaymentsReadinessAPICreateMerchantAccountRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) CreateMerchantAccountExecute(r PaymentsReadinessAPICreateMerchantAccountRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.CreateMerchantAccount")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId is required and must be specified")
	}
	if r.merchantAccountCreateRequest == nil {
		return localVarReturnValue, nil, reportError("merchantAccountCreateRequest is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.idempotencyKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	}
	// body params
	localVarPostBody = r.merchantAccountCreateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPICreateMerchantOnboardingLinkRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	merchantAccountId string
	environment *string
	merchantAccountId2 *string
	merchantOnboardingLinkRequest *MerchantOnboardingLinkRequest
}

func (r PaymentsReadinessAPICreateMerchantOnboardingLinkRequest) Environment(environment string) PaymentsReadinessAPICreateMerchantOnboardingLinkRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPICreateMerchantOnboardingLinkRequest) MerchantAccountId2(merchantAccountId2 string) PaymentsReadinessAPICreateMerchantOnboardingLinkRequest {
	r.merchantAccountId2 = &merchantAccountId2
	return r
}

func (r PaymentsReadinessAPICreateMerchantOnboardingLinkRequest) MerchantOnboardingLinkRequest(merchantOnboardingLinkRequest MerchantOnboardingLinkRequest) PaymentsReadinessAPICreateMerchantOnboardingLinkRequest {
	r.merchantOnboardingLinkRequest = &merchantOnboardingLinkRequest
	return r
}

func (r PaymentsReadinessAPICreateMerchantOnboardingLinkRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.CreateMerchantOnboardingLinkExecute(r)
}

/*
CreateMerchantOnboardingLink Create a hosted merchant onboarding link

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param merchantAccountId
 @return PaymentsReadinessAPICreateMerchantOnboardingLinkRequest
*/
func (a *PaymentsReadinessAPIService) CreateMerchantOnboardingLink(ctx context.Context, merchantAccountId string) PaymentsReadinessAPICreateMerchantOnboardingLinkRequest {
	return PaymentsReadinessAPICreateMerchantOnboardingLinkRequest{
		ApiService: a,
		ctx: ctx,
		merchantAccountId: merchantAccountId,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) CreateMerchantOnboardingLinkExecute(r PaymentsReadinessAPICreateMerchantOnboardingLinkRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.CreateMerchantOnboardingLink")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts/{merchantAccountId}/onboarding-link"
	localVarPath = strings.Replace(localVarPath, "{"+"merchantAccountId"+"}", url.PathEscape(parameterValueToString(r.merchantAccountId, "merchantAccountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId2 == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId2 is required and must be specified")
	}
	if r.merchantOnboardingLinkRequest == nil {
		return localVarReturnValue, nil, reportError("merchantOnboardingLinkRequest is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId2, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.merchantOnboardingLinkRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPIGetMerchantAccountRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	merchantAccountId string
	environment *string
	merchantAccountId2 *string
}

func (r PaymentsReadinessAPIGetMerchantAccountRequest) Environment(environment string) PaymentsReadinessAPIGetMerchantAccountRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountRequest) MerchantAccountId2(merchantAccountId2 string) PaymentsReadinessAPIGetMerchantAccountRequest {
	r.merchantAccountId2 = &merchantAccountId2
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.GetMerchantAccountExecute(r)
}

/*
GetMerchantAccount Get a merchant account snapshot

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param merchantAccountId
 @return PaymentsReadinessAPIGetMerchantAccountRequest
*/
func (a *PaymentsReadinessAPIService) GetMerchantAccount(ctx context.Context, merchantAccountId string) PaymentsReadinessAPIGetMerchantAccountRequest {
	return PaymentsReadinessAPIGetMerchantAccountRequest{
		ApiService: a,
		ctx: ctx,
		merchantAccountId: merchantAccountId,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) GetMerchantAccountExecute(r PaymentsReadinessAPIGetMerchantAccountRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.GetMerchantAccount")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts/{merchantAccountId}"
	localVarPath = strings.Replace(localVarPath, "{"+"merchantAccountId"+"}", url.PathEscape(parameterValueToString(r.merchantAccountId, "merchantAccountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId2 == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId2 is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId2, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPIGetMerchantAccountCapabilitiesRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	merchantAccountId string
	environment *string
	merchantAccountId2 *string
}

func (r PaymentsReadinessAPIGetMerchantAccountCapabilitiesRequest) Environment(environment string) PaymentsReadinessAPIGetMerchantAccountCapabilitiesRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountCapabilitiesRequest) MerchantAccountId2(merchantAccountId2 string) PaymentsReadinessAPIGetMerchantAccountCapabilitiesRequest {
	r.merchantAccountId2 = &merchantAccountId2
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountCapabilitiesRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.GetMerchantAccountCapabilitiesExecute(r)
}

/*
GetMerchantAccountCapabilities Get merchant payments capability state

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param merchantAccountId
 @return PaymentsReadinessAPIGetMerchantAccountCapabilitiesRequest
*/
func (a *PaymentsReadinessAPIService) GetMerchantAccountCapabilities(ctx context.Context, merchantAccountId string) PaymentsReadinessAPIGetMerchantAccountCapabilitiesRequest {
	return PaymentsReadinessAPIGetMerchantAccountCapabilitiesRequest{
		ApiService: a,
		ctx: ctx,
		merchantAccountId: merchantAccountId,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) GetMerchantAccountCapabilitiesExecute(r PaymentsReadinessAPIGetMerchantAccountCapabilitiesRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.GetMerchantAccountCapabilities")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts/{merchantAccountId}/capabilities"
	localVarPath = strings.Replace(localVarPath, "{"+"merchantAccountId"+"}", url.PathEscape(parameterValueToString(r.merchantAccountId, "merchantAccountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId2 == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId2 is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId2, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPIGetMerchantAccountPayoutProfileRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	merchantAccountId string
	environment *string
	merchantAccountId2 *string
}

func (r PaymentsReadinessAPIGetMerchantAccountPayoutProfileRequest) Environment(environment string) PaymentsReadinessAPIGetMerchantAccountPayoutProfileRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountPayoutProfileRequest) MerchantAccountId2(merchantAccountId2 string) PaymentsReadinessAPIGetMerchantAccountPayoutProfileRequest {
	r.merchantAccountId2 = &merchantAccountId2
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountPayoutProfileRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.GetMerchantAccountPayoutProfileExecute(r)
}

/*
GetMerchantAccountPayoutProfile Get merchant payout profile

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param merchantAccountId
 @return PaymentsReadinessAPIGetMerchantAccountPayoutProfileRequest
*/
func (a *PaymentsReadinessAPIService) GetMerchantAccountPayoutProfile(ctx context.Context, merchantAccountId string) PaymentsReadinessAPIGetMerchantAccountPayoutProfileRequest {
	return PaymentsReadinessAPIGetMerchantAccountPayoutProfileRequest{
		ApiService: a,
		ctx: ctx,
		merchantAccountId: merchantAccountId,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) GetMerchantAccountPayoutProfileExecute(r PaymentsReadinessAPIGetMerchantAccountPayoutProfileRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.GetMerchantAccountPayoutProfile")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts/{merchantAccountId}/payout-profile"
	localVarPath = strings.Replace(localVarPath, "{"+"merchantAccountId"+"}", url.PathEscape(parameterValueToString(r.merchantAccountId, "merchantAccountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId2 == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId2 is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId2, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPIGetMerchantAccountPayoutsRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	merchantAccountId string
	environment *string
	merchantAccountId2 *string
	limit *int32
	cursor *string
}

func (r PaymentsReadinessAPIGetMerchantAccountPayoutsRequest) Environment(environment string) PaymentsReadinessAPIGetMerchantAccountPayoutsRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountPayoutsRequest) MerchantAccountId2(merchantAccountId2 string) PaymentsReadinessAPIGetMerchantAccountPayoutsRequest {
	r.merchantAccountId2 = &merchantAccountId2
	return r
}

// Page size, 1-100. Omitting both limit and cursor returns the full unpaginated list.
func (r PaymentsReadinessAPIGetMerchantAccountPayoutsRequest) Limit(limit int32) PaymentsReadinessAPIGetMerchantAccountPayoutsRequest {
	r.limit = &limit
	return r
}

// Opaque cursor from the previous page&#39;s nextCursor. Pass it back verbatim to fetch the next page.
func (r PaymentsReadinessAPIGetMerchantAccountPayoutsRequest) Cursor(cursor string) PaymentsReadinessAPIGetMerchantAccountPayoutsRequest {
	r.cursor = &cursor
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountPayoutsRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.GetMerchantAccountPayoutsExecute(r)
}

/*
GetMerchantAccountPayouts List merchant payouts

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param merchantAccountId
 @return PaymentsReadinessAPIGetMerchantAccountPayoutsRequest
*/
func (a *PaymentsReadinessAPIService) GetMerchantAccountPayouts(ctx context.Context, merchantAccountId string) PaymentsReadinessAPIGetMerchantAccountPayoutsRequest {
	return PaymentsReadinessAPIGetMerchantAccountPayoutsRequest{
		ApiService: a,
		ctx: ctx,
		merchantAccountId: merchantAccountId,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) GetMerchantAccountPayoutsExecute(r PaymentsReadinessAPIGetMerchantAccountPayoutsRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.GetMerchantAccountPayouts")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts/{merchantAccountId}/payouts"
	localVarPath = strings.Replace(localVarPath, "{"+"merchantAccountId"+"}", url.PathEscape(parameterValueToString(r.merchantAccountId, "merchantAccountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId2 == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId2 is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId2, "form", "")
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPIGetMerchantAccountSettlementsRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	merchantAccountId string
	environment *string
	merchantAccountId2 *string
	scope *string
	limit *int32
	cursor *string
}

func (r PaymentsReadinessAPIGetMerchantAccountSettlementsRequest) Environment(environment string) PaymentsReadinessAPIGetMerchantAccountSettlementsRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountSettlementsRequest) MerchantAccountId2(merchantAccountId2 string) PaymentsReadinessAPIGetMerchantAccountSettlementsRequest {
	r.merchantAccountId2 = &merchantAccountId2
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountSettlementsRequest) Scope(scope string) PaymentsReadinessAPIGetMerchantAccountSettlementsRequest {
	r.scope = &scope
	return r
}

// Page size, 1-100. Omitting both limit and cursor returns the full unpaginated list.
func (r PaymentsReadinessAPIGetMerchantAccountSettlementsRequest) Limit(limit int32) PaymentsReadinessAPIGetMerchantAccountSettlementsRequest {
	r.limit = &limit
	return r
}

// Opaque cursor from the previous page&#39;s nextCursor. Pass it back verbatim to fetch the next page.
func (r PaymentsReadinessAPIGetMerchantAccountSettlementsRequest) Cursor(cursor string) PaymentsReadinessAPIGetMerchantAccountSettlementsRequest {
	r.cursor = &cursor
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountSettlementsRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.GetMerchantAccountSettlementsExecute(r)
}

/*
GetMerchantAccountSettlements List merchant settlements

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param merchantAccountId
 @return PaymentsReadinessAPIGetMerchantAccountSettlementsRequest
*/
func (a *PaymentsReadinessAPIService) GetMerchantAccountSettlements(ctx context.Context, merchantAccountId string) PaymentsReadinessAPIGetMerchantAccountSettlementsRequest {
	return PaymentsReadinessAPIGetMerchantAccountSettlementsRequest{
		ApiService: a,
		ctx: ctx,
		merchantAccountId: merchantAccountId,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) GetMerchantAccountSettlementsExecute(r PaymentsReadinessAPIGetMerchantAccountSettlementsRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.GetMerchantAccountSettlements")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts/{merchantAccountId}/settlements"
	localVarPath = strings.Replace(localVarPath, "{"+"merchantAccountId"+"}", url.PathEscape(parameterValueToString(r.merchantAccountId, "merchantAccountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId2 == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId2 is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId2, "form", "")
	if r.scope != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "scope", r.scope, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPIGetMerchantAccountStateRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	merchantAccountId string
	environment *string
	merchantAccountId2 *string
}

func (r PaymentsReadinessAPIGetMerchantAccountStateRequest) Environment(environment string) PaymentsReadinessAPIGetMerchantAccountStateRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountStateRequest) MerchantAccountId2(merchantAccountId2 string) PaymentsReadinessAPIGetMerchantAccountStateRequest {
	r.merchantAccountId2 = &merchantAccountId2
	return r
}

func (r PaymentsReadinessAPIGetMerchantAccountStateRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.GetMerchantAccountStateExecute(r)
}

/*
GetMerchantAccountState Get merchant payments readiness state

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param merchantAccountId
 @return PaymentsReadinessAPIGetMerchantAccountStateRequest
*/
func (a *PaymentsReadinessAPIService) GetMerchantAccountState(ctx context.Context, merchantAccountId string) PaymentsReadinessAPIGetMerchantAccountStateRequest {
	return PaymentsReadinessAPIGetMerchantAccountStateRequest{
		ApiService: a,
		ctx: ctx,
		merchantAccountId: merchantAccountId,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) GetMerchantAccountStateExecute(r PaymentsReadinessAPIGetMerchantAccountStateRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.GetMerchantAccountState")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts/{merchantAccountId}/state"
	localVarPath = strings.Replace(localVarPath, "{"+"merchantAccountId"+"}", url.PathEscape(parameterValueToString(r.merchantAccountId, "merchantAccountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId2 == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId2 is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId2, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPIGetMerchantOnboardingRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	merchantAccountId string
	onboardingId string
	environment *string
	merchantAccountId2 *string
}

func (r PaymentsReadinessAPIGetMerchantOnboardingRequest) Environment(environment string) PaymentsReadinessAPIGetMerchantOnboardingRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPIGetMerchantOnboardingRequest) MerchantAccountId2(merchantAccountId2 string) PaymentsReadinessAPIGetMerchantOnboardingRequest {
	r.merchantAccountId2 = &merchantAccountId2
	return r
}

func (r PaymentsReadinessAPIGetMerchantOnboardingRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.GetMerchantOnboardingExecute(r)
}

/*
GetMerchantOnboarding Get onboarding session state and outstanding requirements

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param merchantAccountId
 @param onboardingId
 @return PaymentsReadinessAPIGetMerchantOnboardingRequest
*/
func (a *PaymentsReadinessAPIService) GetMerchantOnboarding(ctx context.Context, merchantAccountId string, onboardingId string) PaymentsReadinessAPIGetMerchantOnboardingRequest {
	return PaymentsReadinessAPIGetMerchantOnboardingRequest{
		ApiService: a,
		ctx: ctx,
		merchantAccountId: merchantAccountId,
		onboardingId: onboardingId,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) GetMerchantOnboardingExecute(r PaymentsReadinessAPIGetMerchantOnboardingRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.GetMerchantOnboarding")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts/{merchantAccountId}/onboarding/{onboardingId}"
	localVarPath = strings.Replace(localVarPath, "{"+"merchantAccountId"+"}", url.PathEscape(parameterValueToString(r.merchantAccountId, "merchantAccountId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"onboardingId"+"}", url.PathEscape(parameterValueToString(r.onboardingId, "onboardingId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId2 == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId2 is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId2, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPIListMerchantAccountsRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	environment *string
	merchantAccountId *string
	limit *string
	cursor *string
}

func (r PaymentsReadinessAPIListMerchantAccountsRequest) Environment(environment string) PaymentsReadinessAPIListMerchantAccountsRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPIListMerchantAccountsRequest) MerchantAccountId(merchantAccountId string) PaymentsReadinessAPIListMerchantAccountsRequest {
	r.merchantAccountId = &merchantAccountId
	return r
}

func (r PaymentsReadinessAPIListMerchantAccountsRequest) Limit(limit string) PaymentsReadinessAPIListMerchantAccountsRequest {
	r.limit = &limit
	return r
}

func (r PaymentsReadinessAPIListMerchantAccountsRequest) Cursor(cursor string) PaymentsReadinessAPIListMerchantAccountsRequest {
	r.cursor = &cursor
	return r
}

func (r PaymentsReadinessAPIListMerchantAccountsRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.ListMerchantAccountsExecute(r)
}

/*
ListMerchantAccounts List merchant accounts for the caller's organization

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return PaymentsReadinessAPIListMerchantAccountsRequest
*/
func (a *PaymentsReadinessAPIService) ListMerchantAccounts(ctx context.Context) PaymentsReadinessAPIListMerchantAccountsRequest {
	return PaymentsReadinessAPIListMerchantAccountsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) ListMerchantAccountsExecute(r PaymentsReadinessAPIListMerchantAccountsRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.ListMerchantAccounts")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId, "form", "")
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPISubmitMerchantOnboardingRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	merchantAccountId string
	environment *string
	merchantAccountId2 *string
	merchantOnboardingSubmitRequest *MerchantOnboardingSubmitRequest
	idempotencyKey *string
}

func (r PaymentsReadinessAPISubmitMerchantOnboardingRequest) Environment(environment string) PaymentsReadinessAPISubmitMerchantOnboardingRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPISubmitMerchantOnboardingRequest) MerchantAccountId2(merchantAccountId2 string) PaymentsReadinessAPISubmitMerchantOnboardingRequest {
	r.merchantAccountId2 = &merchantAccountId2
	return r
}

func (r PaymentsReadinessAPISubmitMerchantOnboardingRequest) MerchantOnboardingSubmitRequest(merchantOnboardingSubmitRequest MerchantOnboardingSubmitRequest) PaymentsReadinessAPISubmitMerchantOnboardingRequest {
	r.merchantOnboardingSubmitRequest = &merchantOnboardingSubmitRequest
	return r
}

// Required for production-safe retries on mutating routes. Reusing a key with a different request body returns 409.
func (r PaymentsReadinessAPISubmitMerchantOnboardingRequest) IdempotencyKey(idempotencyKey string) PaymentsReadinessAPISubmitMerchantOnboardingRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r PaymentsReadinessAPISubmitMerchantOnboardingRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.SubmitMerchantOnboardingExecute(r)
}

/*
SubmitMerchantOnboarding Submit a draft merchant for underwriting — the activation step after create

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param merchantAccountId
 @return PaymentsReadinessAPISubmitMerchantOnboardingRequest
*/
func (a *PaymentsReadinessAPIService) SubmitMerchantOnboarding(ctx context.Context, merchantAccountId string) PaymentsReadinessAPISubmitMerchantOnboardingRequest {
	return PaymentsReadinessAPISubmitMerchantOnboardingRequest{
		ApiService: a,
		ctx: ctx,
		merchantAccountId: merchantAccountId,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) SubmitMerchantOnboardingExecute(r PaymentsReadinessAPISubmitMerchantOnboardingRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.SubmitMerchantOnboarding")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts/{merchantAccountId}/onboarding/submit"
	localVarPath = strings.Replace(localVarPath, "{"+"merchantAccountId"+"}", url.PathEscape(parameterValueToString(r.merchantAccountId, "merchantAccountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId2 == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId2 is required and must be specified")
	}
	if r.merchantOnboardingSubmitRequest == nil {
		return localVarReturnValue, nil, reportError("merchantOnboardingSubmitRequest is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId2, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.idempotencyKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	}
	// body params
	localVarPostBody = r.merchantOnboardingSubmitRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PaymentsReadinessAPIUpdateMerchantAccountRequest struct {
	ctx context.Context
	ApiService *PaymentsReadinessAPIService
	merchantAccountId string
	environment *string
	merchantAccountId2 *string
	merchantAccountUpdateRequest *MerchantAccountUpdateRequest
	idempotencyKey *string
}

func (r PaymentsReadinessAPIUpdateMerchantAccountRequest) Environment(environment string) PaymentsReadinessAPIUpdateMerchantAccountRequest {
	r.environment = &environment
	return r
}

func (r PaymentsReadinessAPIUpdateMerchantAccountRequest) MerchantAccountId2(merchantAccountId2 string) PaymentsReadinessAPIUpdateMerchantAccountRequest {
	r.merchantAccountId2 = &merchantAccountId2
	return r
}

func (r PaymentsReadinessAPIUpdateMerchantAccountRequest) MerchantAccountUpdateRequest(merchantAccountUpdateRequest MerchantAccountUpdateRequest) PaymentsReadinessAPIUpdateMerchantAccountRequest {
	r.merchantAccountUpdateRequest = &merchantAccountUpdateRequest
	return r
}

// Required for production-safe retries on mutating routes. Reusing a key with a different request body returns 409.
func (r PaymentsReadinessAPIUpdateMerchantAccountRequest) IdempotencyKey(idempotencyKey string) PaymentsReadinessAPIUpdateMerchantAccountRequest {
	r.idempotencyKey = &idempotencyKey
	return r
}

func (r PaymentsReadinessAPIUpdateMerchantAccountRequest) Execute() (*ApiWriteEnvelope, *http.Response, error) {
	return r.ApiService.UpdateMerchantAccountExecute(r)
}

/*
UpdateMerchantAccount Update merchant account profile fields (draft-friendly)

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param merchantAccountId
 @return PaymentsReadinessAPIUpdateMerchantAccountRequest
*/
func (a *PaymentsReadinessAPIService) UpdateMerchantAccount(ctx context.Context, merchantAccountId string) PaymentsReadinessAPIUpdateMerchantAccountRequest {
	return PaymentsReadinessAPIUpdateMerchantAccountRequest{
		ApiService: a,
		ctx: ctx,
		merchantAccountId: merchantAccountId,
	}
}

// Execute executes the request
//  @return ApiWriteEnvelope
func (a *PaymentsReadinessAPIService) UpdateMerchantAccountExecute(r PaymentsReadinessAPIUpdateMerchantAccountRequest) (*ApiWriteEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiWriteEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsReadinessAPIService.UpdateMerchantAccount")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/merchant-accounts/{merchantAccountId}"
	localVarPath = strings.Replace(localVarPath, "{"+"merchantAccountId"+"}", url.PathEscape(parameterValueToString(r.merchantAccountId, "merchantAccountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.environment == nil {
		return localVarReturnValue, nil, reportError("environment is required and must be specified")
	}
	if r.merchantAccountId2 == nil {
		return localVarReturnValue, nil, reportError("merchantAccountId2 is required and must be specified")
	}
	if r.merchantAccountUpdateRequest == nil {
		return localVarReturnValue, nil, reportError("merchantAccountUpdateRequest is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "merchantAccountId", r.merchantAccountId2, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.idempotencyKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Idempotency-Key", r.idempotencyKey, "simple", "")
	}
	// body params
	localVarPostBody = r.merchantAccountUpdateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
