/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortex

import (
	"encoding/json"
)

// checks if the BillingOrderAmendRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingOrderAmendRequest{}

// BillingOrderAmendRequest struct for BillingOrderAmendRequest
type BillingOrderAmendRequest struct {
	// Restatement lines for the amendment's first draft version. Omit to clone the target subscription's live items; an empty array signs an early termination.
	Lines []BillingQuoteLineInput `json:"lines,omitempty"`
	CouponIds []string `json:"couponIds,omitempty"`
	Terms *string `json:"terms,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

// NewBillingOrderAmendRequest instantiates a new BillingOrderAmendRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingOrderAmendRequest() *BillingOrderAmendRequest {
	this := BillingOrderAmendRequest{}
	return &this
}

// NewBillingOrderAmendRequestWithDefaults instantiates a new BillingOrderAmendRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingOrderAmendRequestWithDefaults() *BillingOrderAmendRequest {
	this := BillingOrderAmendRequest{}
	return &this
}

// GetLines returns the Lines field value if set, zero value otherwise.
func (o *BillingOrderAmendRequest) GetLines() []BillingQuoteLineInput {
	if o == nil || IsNil(o.Lines) {
		var ret []BillingQuoteLineInput
		return ret
	}
	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingOrderAmendRequest) GetLinesOk() ([]BillingQuoteLineInput, bool) {
	if o == nil || IsNil(o.Lines) {
		return nil, false
	}
	return o.Lines, true
}

// HasLines returns a boolean if a field has been set.
func (o *BillingOrderAmendRequest) HasLines() bool {
	if o != nil && !IsNil(o.Lines) {
		return true
	}

	return false
}

// SetLines gets a reference to the given []BillingQuoteLineInput and assigns it to the Lines field.
func (o *BillingOrderAmendRequest) SetLines(v []BillingQuoteLineInput) {
	o.Lines = v
}

// GetCouponIds returns the CouponIds field value if set, zero value otherwise.
func (o *BillingOrderAmendRequest) GetCouponIds() []string {
	if o == nil || IsNil(o.CouponIds) {
		var ret []string
		return ret
	}
	return o.CouponIds
}

// GetCouponIdsOk returns a tuple with the CouponIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingOrderAmendRequest) GetCouponIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.CouponIds) {
		return nil, false
	}
	return o.CouponIds, true
}

// HasCouponIds returns a boolean if a field has been set.
func (o *BillingOrderAmendRequest) HasCouponIds() bool {
	if o != nil && !IsNil(o.CouponIds) {
		return true
	}

	return false
}

// SetCouponIds gets a reference to the given []string and assigns it to the CouponIds field.
func (o *BillingOrderAmendRequest) SetCouponIds(v []string) {
	o.CouponIds = v
}

// GetTerms returns the Terms field value if set, zero value otherwise.
func (o *BillingOrderAmendRequest) GetTerms() string {
	if o == nil || IsNil(o.Terms) {
		var ret string
		return ret
	}
	return *o.Terms
}

// GetTermsOk returns a tuple with the Terms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingOrderAmendRequest) GetTermsOk() (*string, bool) {
	if o == nil || IsNil(o.Terms) {
		return nil, false
	}
	return o.Terms, true
}

// HasTerms returns a boolean if a field has been set.
func (o *BillingOrderAmendRequest) HasTerms() bool {
	if o != nil && !IsNil(o.Terms) {
		return true
	}

	return false
}

// SetTerms gets a reference to the given string and assigns it to the Terms field.
func (o *BillingOrderAmendRequest) SetTerms(v string) {
	o.Terms = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *BillingOrderAmendRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingOrderAmendRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *BillingOrderAmendRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *BillingOrderAmendRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o BillingOrderAmendRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingOrderAmendRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Lines) {
		toSerialize["lines"] = o.Lines
	}
	if !IsNil(o.CouponIds) {
		toSerialize["couponIds"] = o.CouponIds
	}
	if !IsNil(o.Terms) {
		toSerialize["terms"] = o.Terms
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableBillingOrderAmendRequest struct {
	value *BillingOrderAmendRequest
	isSet bool
}

func (v NullableBillingOrderAmendRequest) Get() *BillingOrderAmendRequest {
	return v.value
}

func (v *NullableBillingOrderAmendRequest) Set(val *BillingOrderAmendRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingOrderAmendRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingOrderAmendRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingOrderAmendRequest(val *BillingOrderAmendRequest) *NullableBillingOrderAmendRequest {
	return &NullableBillingOrderAmendRequest{value: val, isSet: true}
}

func (v NullableBillingOrderAmendRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingOrderAmendRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
