/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsageThresholdCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageThresholdCreateRequest{}

// UsageThresholdCreateRequest struct for UsageThresholdCreateRequest
type UsageThresholdCreateRequest struct {
	MeterId string `json:"meterId"`
	CustomerId *string `json:"customerId,omitempty"`
	ThresholdValue int32 `json:"thresholdValue"`
	ThresholdId *string `json:"thresholdId,omitempty"`
}

type _UsageThresholdCreateRequest UsageThresholdCreateRequest

// NewUsageThresholdCreateRequest instantiates a new UsageThresholdCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageThresholdCreateRequest(meterId string, thresholdValue int32) *UsageThresholdCreateRequest {
	this := UsageThresholdCreateRequest{}
	this.MeterId = meterId
	this.ThresholdValue = thresholdValue
	return &this
}

// NewUsageThresholdCreateRequestWithDefaults instantiates a new UsageThresholdCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageThresholdCreateRequestWithDefaults() *UsageThresholdCreateRequest {
	this := UsageThresholdCreateRequest{}
	return &this
}

// GetMeterId returns the MeterId field value
func (o *UsageThresholdCreateRequest) GetMeterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MeterId
}

// GetMeterIdOk returns a tuple with the MeterId field value
// and a boolean to check if the value has been set.
func (o *UsageThresholdCreateRequest) GetMeterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MeterId, true
}

// SetMeterId sets field value
func (o *UsageThresholdCreateRequest) SetMeterId(v string) {
	o.MeterId = v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *UsageThresholdCreateRequest) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageThresholdCreateRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *UsageThresholdCreateRequest) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *UsageThresholdCreateRequest) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetThresholdValue returns the ThresholdValue field value
func (o *UsageThresholdCreateRequest) GetThresholdValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ThresholdValue
}

// GetThresholdValueOk returns a tuple with the ThresholdValue field value
// and a boolean to check if the value has been set.
func (o *UsageThresholdCreateRequest) GetThresholdValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThresholdValue, true
}

// SetThresholdValue sets field value
func (o *UsageThresholdCreateRequest) SetThresholdValue(v int32) {
	o.ThresholdValue = v
}

// GetThresholdId returns the ThresholdId field value if set, zero value otherwise.
func (o *UsageThresholdCreateRequest) GetThresholdId() string {
	if o == nil || IsNil(o.ThresholdId) {
		var ret string
		return ret
	}
	return *o.ThresholdId
}

// GetThresholdIdOk returns a tuple with the ThresholdId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageThresholdCreateRequest) GetThresholdIdOk() (*string, bool) {
	if o == nil || IsNil(o.ThresholdId) {
		return nil, false
	}
	return o.ThresholdId, true
}

// HasThresholdId returns a boolean if a field has been set.
func (o *UsageThresholdCreateRequest) HasThresholdId() bool {
	if o != nil && !IsNil(o.ThresholdId) {
		return true
	}

	return false
}

// SetThresholdId gets a reference to the given string and assigns it to the ThresholdId field.
func (o *UsageThresholdCreateRequest) SetThresholdId(v string) {
	o.ThresholdId = &v
}

func (o UsageThresholdCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageThresholdCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meterId"] = o.MeterId
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	toSerialize["thresholdValue"] = o.ThresholdValue
	if !IsNil(o.ThresholdId) {
		toSerialize["thresholdId"] = o.ThresholdId
	}
	return toSerialize, nil
}

func (o *UsageThresholdCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meterId",
		"thresholdValue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageThresholdCreateRequest := _UsageThresholdCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageThresholdCreateRequest)

	if err != nil {
		return err
	}

	*o = UsageThresholdCreateRequest(varUsageThresholdCreateRequest)

	return err
}

type NullableUsageThresholdCreateRequest struct {
	value *UsageThresholdCreateRequest
	isSet bool
}

func (v NullableUsageThresholdCreateRequest) Get() *UsageThresholdCreateRequest {
	return v.value
}

func (v *NullableUsageThresholdCreateRequest) Set(val *UsageThresholdCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageThresholdCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageThresholdCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageThresholdCreateRequest(val *UsageThresholdCreateRequest) *NullableUsageThresholdCreateRequest {
	return &NullableUsageThresholdCreateRequest{value: val, isSet: true}
}

func (v NullableUsageThresholdCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageThresholdCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
