/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomerPaymentMethodVerifyMicrodepositRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerPaymentMethodVerifyMicrodepositRequest{}

// CustomerPaymentMethodVerifyMicrodepositRequest struct for CustomerPaymentMethodVerifyMicrodepositRequest
type CustomerPaymentMethodVerifyMicrodepositRequest struct {
	BillingAccountId *string `json:"billingAccountId,omitempty"`
	// The FNX-prefixed code from the buyer's bank statement descriptor.
	VerificationCode string `json:"verificationCode"`
}

type _CustomerPaymentMethodVerifyMicrodepositRequest CustomerPaymentMethodVerifyMicrodepositRequest

// NewCustomerPaymentMethodVerifyMicrodepositRequest instantiates a new CustomerPaymentMethodVerifyMicrodepositRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerPaymentMethodVerifyMicrodepositRequest(verificationCode string) *CustomerPaymentMethodVerifyMicrodepositRequest {
	this := CustomerPaymentMethodVerifyMicrodepositRequest{}
	this.VerificationCode = verificationCode
	return &this
}

// NewCustomerPaymentMethodVerifyMicrodepositRequestWithDefaults instantiates a new CustomerPaymentMethodVerifyMicrodepositRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerPaymentMethodVerifyMicrodepositRequestWithDefaults() *CustomerPaymentMethodVerifyMicrodepositRequest {
	this := CustomerPaymentMethodVerifyMicrodepositRequest{}
	return &this
}

// GetBillingAccountId returns the BillingAccountId field value if set, zero value otherwise.
func (o *CustomerPaymentMethodVerifyMicrodepositRequest) GetBillingAccountId() string {
	if o == nil || IsNil(o.BillingAccountId) {
		var ret string
		return ret
	}
	return *o.BillingAccountId
}

// GetBillingAccountIdOk returns a tuple with the BillingAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodVerifyMicrodepositRequest) GetBillingAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.BillingAccountId) {
		return nil, false
	}
	return o.BillingAccountId, true
}

// HasBillingAccountId returns a boolean if a field has been set.
func (o *CustomerPaymentMethodVerifyMicrodepositRequest) HasBillingAccountId() bool {
	if o != nil && !IsNil(o.BillingAccountId) {
		return true
	}

	return false
}

// SetBillingAccountId gets a reference to the given string and assigns it to the BillingAccountId field.
func (o *CustomerPaymentMethodVerifyMicrodepositRequest) SetBillingAccountId(v string) {
	o.BillingAccountId = &v
}

// GetVerificationCode returns the VerificationCode field value
func (o *CustomerPaymentMethodVerifyMicrodepositRequest) GetVerificationCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationCode
}

// GetVerificationCodeOk returns a tuple with the VerificationCode field value
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodVerifyMicrodepositRequest) GetVerificationCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationCode, true
}

// SetVerificationCode sets field value
func (o *CustomerPaymentMethodVerifyMicrodepositRequest) SetVerificationCode(v string) {
	o.VerificationCode = v
}

func (o CustomerPaymentMethodVerifyMicrodepositRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerPaymentMethodVerifyMicrodepositRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BillingAccountId) {
		toSerialize["billingAccountId"] = o.BillingAccountId
	}
	toSerialize["verificationCode"] = o.VerificationCode
	return toSerialize, nil
}

func (o *CustomerPaymentMethodVerifyMicrodepositRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"verificationCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerPaymentMethodVerifyMicrodepositRequest := _CustomerPaymentMethodVerifyMicrodepositRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomerPaymentMethodVerifyMicrodepositRequest)

	if err != nil {
		return err
	}

	*o = CustomerPaymentMethodVerifyMicrodepositRequest(varCustomerPaymentMethodVerifyMicrodepositRequest)

	return err
}

type NullableCustomerPaymentMethodVerifyMicrodepositRequest struct {
	value *CustomerPaymentMethodVerifyMicrodepositRequest
	isSet bool
}

func (v NullableCustomerPaymentMethodVerifyMicrodepositRequest) Get() *CustomerPaymentMethodVerifyMicrodepositRequest {
	return v.value
}

func (v *NullableCustomerPaymentMethodVerifyMicrodepositRequest) Set(val *CustomerPaymentMethodVerifyMicrodepositRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerPaymentMethodVerifyMicrodepositRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerPaymentMethodVerifyMicrodepositRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerPaymentMethodVerifyMicrodepositRequest(val *CustomerPaymentMethodVerifyMicrodepositRequest) *NullableCustomerPaymentMethodVerifyMicrodepositRequest {
	return &NullableCustomerPaymentMethodVerifyMicrodepositRequest{value: val, isSet: true}
}

func (v NullableCustomerPaymentMethodVerifyMicrodepositRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerPaymentMethodVerifyMicrodepositRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
