/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomerCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerCreateRequest{}

// CustomerCreateRequest struct for CustomerCreateRequest
type CustomerCreateRequest struct {
	Name string `json:"name"`
	DefaultCurrency string `json:"defaultCurrency"`
	// Caller-chosen Vortex customer id; omit to auto-mint.
	CustomerId *string `json:"customerId,omitempty"`
	// Merchant's own customer reference — the portable join key across Vortex surfaces.
	ExternalCustomerRef *string `json:"externalCustomerRef,omitempty"`
	Email *string `json:"email,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

type _CustomerCreateRequest CustomerCreateRequest

// NewCustomerCreateRequest instantiates a new CustomerCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerCreateRequest(name string, defaultCurrency string) *CustomerCreateRequest {
	this := CustomerCreateRequest{}
	this.Name = name
	this.DefaultCurrency = defaultCurrency
	return &this
}

// NewCustomerCreateRequestWithDefaults instantiates a new CustomerCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerCreateRequestWithDefaults() *CustomerCreateRequest {
	this := CustomerCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CustomerCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CustomerCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CustomerCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDefaultCurrency returns the DefaultCurrency field value
func (o *CustomerCreateRequest) GetDefaultCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultCurrency
}

// GetDefaultCurrencyOk returns a tuple with the DefaultCurrency field value
// and a boolean to check if the value has been set.
func (o *CustomerCreateRequest) GetDefaultCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultCurrency, true
}

// SetDefaultCurrency sets field value
func (o *CustomerCreateRequest) SetDefaultCurrency(v string) {
	o.DefaultCurrency = v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *CustomerCreateRequest) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerCreateRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CustomerCreateRequest) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *CustomerCreateRequest) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetExternalCustomerRef returns the ExternalCustomerRef field value if set, zero value otherwise.
func (o *CustomerCreateRequest) GetExternalCustomerRef() string {
	if o == nil || IsNil(o.ExternalCustomerRef) {
		var ret string
		return ret
	}
	return *o.ExternalCustomerRef
}

// GetExternalCustomerRefOk returns a tuple with the ExternalCustomerRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerCreateRequest) GetExternalCustomerRefOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalCustomerRef) {
		return nil, false
	}
	return o.ExternalCustomerRef, true
}

// HasExternalCustomerRef returns a boolean if a field has been set.
func (o *CustomerCreateRequest) HasExternalCustomerRef() bool {
	if o != nil && !IsNil(o.ExternalCustomerRef) {
		return true
	}

	return false
}

// SetExternalCustomerRef gets a reference to the given string and assigns it to the ExternalCustomerRef field.
func (o *CustomerCreateRequest) SetExternalCustomerRef(v string) {
	o.ExternalCustomerRef = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CustomerCreateRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerCreateRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CustomerCreateRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CustomerCreateRequest) SetEmail(v string) {
	o.Email = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CustomerCreateRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerCreateRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CustomerCreateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *CustomerCreateRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o CustomerCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["defaultCurrency"] = o.DefaultCurrency
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.ExternalCustomerRef) {
		toSerialize["externalCustomerRef"] = o.ExternalCustomerRef
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *CustomerCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"defaultCurrency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerCreateRequest := _CustomerCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomerCreateRequest)

	if err != nil {
		return err
	}

	*o = CustomerCreateRequest(varCustomerCreateRequest)

	return err
}

type NullableCustomerCreateRequest struct {
	value *CustomerCreateRequest
	isSet bool
}

func (v NullableCustomerCreateRequest) Get() *CustomerCreateRequest {
	return v.value
}

func (v *NullableCustomerCreateRequest) Set(val *CustomerCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerCreateRequest(val *CustomerCreateRequest) *NullableCustomerCreateRequest {
	return &NullableCustomerCreateRequest{value: val, isSet: true}
}

func (v NullableCustomerCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
