/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MerchantAccountCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantAccountCreateRequest{}

// MerchantAccountCreateRequest struct for MerchantAccountCreateRequest
type MerchantAccountCreateRequest struct {
	Environment string `json:"environment"`
	// Your stable reference for this merchant. Optional; generated when omitted.
	ExternalMerchantRef *string `json:"externalMerchantRef,omitempty"`
	DisplayName string `json:"displayName"`
	LegalEntityType string `json:"legalEntityType"`
	Country string `json:"country"`
	MerchantMode string `json:"merchantMode"`
	DefaultCurrency string `json:"defaultCurrency"`
	// Must match the caller's organization when present; rejected otherwise.
	TenantId *string `json:"tenantId,omitempty"`
	// Connect: provision this account as a linked sub-merchant under an operator-granted platform account the caller controls (sandbox only in v1). The account is created in a fresh claimable org; the response carries `claimUrl`/`claimExpiresAt` for handing ownership to the sub-merchant.
	PlatformMerchantAccountId *string `json:"platformMerchantAccountId,omitempty"`
	DoingBusinessAs *string `json:"doingBusinessAs,omitempty"`
	BusinessPhone *string `json:"businessPhone,omitempty"`
	BusinessTaxId *string `json:"businessTaxId,omitempty"`
	Phone *string `json:"phone,omitempty"`
	TaxId *string `json:"taxId,omitempty"`
	Email *string `json:"email,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName *string `json:"lastName,omitempty"`
	Mcc *string `json:"mcc,omitempty"`
	Url *string `json:"url,omitempty"`
	MaxTransactionAmount *float32 `json:"maxTransactionAmount,omitempty"`
	AchMaxTransactionAmount *float32 `json:"achMaxTransactionAmount,omitempty"`
	AnnualCardVolume *float32 `json:"annualCardVolume,omitempty"`
	PrincipalPercentageOwnership *float32 `json:"principalPercentageOwnership,omitempty"`
	HasAcceptedCreditCardsPreviously *bool `json:"hasAcceptedCreditCardsPreviously,omitempty"`
	DateOfBirth *MerchantProfileDate `json:"dateOfBirth,omitempty"`
	IncorporationDate *MerchantProfileDate `json:"incorporationDate,omitempty"`
	BusinessAddress *MerchantAddress `json:"businessAddress,omitempty"`
	PersonalAddress *MerchantAddress `json:"personalAddress,omitempty"`
	SettlementBankAccount *MerchantSettlementBankAccount `json:"settlementBankAccount,omitempty"`
	AssociatedIdentities []MerchantAssociatedIdentity `json:"associatedIdentities,omitempty"`
	Underwriting *MerchantUnderwritingData `json:"underwriting,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

type _MerchantAccountCreateRequest MerchantAccountCreateRequest

// NewMerchantAccountCreateRequest instantiates a new MerchantAccountCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantAccountCreateRequest(environment string, displayName string, legalEntityType string, country string, merchantMode string, defaultCurrency string) *MerchantAccountCreateRequest {
	this := MerchantAccountCreateRequest{}
	this.Environment = environment
	this.DisplayName = displayName
	this.LegalEntityType = legalEntityType
	this.Country = country
	this.MerchantMode = merchantMode
	this.DefaultCurrency = defaultCurrency
	return &this
}

// NewMerchantAccountCreateRequestWithDefaults instantiates a new MerchantAccountCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantAccountCreateRequestWithDefaults() *MerchantAccountCreateRequest {
	this := MerchantAccountCreateRequest{}
	return &this
}

// GetEnvironment returns the Environment field value
func (o *MerchantAccountCreateRequest) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *MerchantAccountCreateRequest) SetEnvironment(v string) {
	o.Environment = v
}

// GetExternalMerchantRef returns the ExternalMerchantRef field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetExternalMerchantRef() string {
	if o == nil || IsNil(o.ExternalMerchantRef) {
		var ret string
		return ret
	}
	return *o.ExternalMerchantRef
}

// GetExternalMerchantRefOk returns a tuple with the ExternalMerchantRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetExternalMerchantRefOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalMerchantRef) {
		return nil, false
	}
	return o.ExternalMerchantRef, true
}

// HasExternalMerchantRef returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasExternalMerchantRef() bool {
	if o != nil && !IsNil(o.ExternalMerchantRef) {
		return true
	}

	return false
}

// SetExternalMerchantRef gets a reference to the given string and assigns it to the ExternalMerchantRef field.
func (o *MerchantAccountCreateRequest) SetExternalMerchantRef(v string) {
	o.ExternalMerchantRef = &v
}

// GetDisplayName returns the DisplayName field value
func (o *MerchantAccountCreateRequest) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *MerchantAccountCreateRequest) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetLegalEntityType returns the LegalEntityType field value
func (o *MerchantAccountCreateRequest) GetLegalEntityType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LegalEntityType
}

// GetLegalEntityTypeOk returns a tuple with the LegalEntityType field value
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetLegalEntityTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LegalEntityType, true
}

// SetLegalEntityType sets field value
func (o *MerchantAccountCreateRequest) SetLegalEntityType(v string) {
	o.LegalEntityType = v
}

// GetCountry returns the Country field value
func (o *MerchantAccountCreateRequest) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *MerchantAccountCreateRequest) SetCountry(v string) {
	o.Country = v
}

// GetMerchantMode returns the MerchantMode field value
func (o *MerchantAccountCreateRequest) GetMerchantMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantMode
}

// GetMerchantModeOk returns a tuple with the MerchantMode field value
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetMerchantModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantMode, true
}

// SetMerchantMode sets field value
func (o *MerchantAccountCreateRequest) SetMerchantMode(v string) {
	o.MerchantMode = v
}

// GetDefaultCurrency returns the DefaultCurrency field value
func (o *MerchantAccountCreateRequest) GetDefaultCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultCurrency
}

// GetDefaultCurrencyOk returns a tuple with the DefaultCurrency field value
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetDefaultCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultCurrency, true
}

// SetDefaultCurrency sets field value
func (o *MerchantAccountCreateRequest) SetDefaultCurrency(v string) {
	o.DefaultCurrency = v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *MerchantAccountCreateRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetPlatformMerchantAccountId returns the PlatformMerchantAccountId field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetPlatformMerchantAccountId() string {
	if o == nil || IsNil(o.PlatformMerchantAccountId) {
		var ret string
		return ret
	}
	return *o.PlatformMerchantAccountId
}

// GetPlatformMerchantAccountIdOk returns a tuple with the PlatformMerchantAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetPlatformMerchantAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlatformMerchantAccountId) {
		return nil, false
	}
	return o.PlatformMerchantAccountId, true
}

// HasPlatformMerchantAccountId returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasPlatformMerchantAccountId() bool {
	if o != nil && !IsNil(o.PlatformMerchantAccountId) {
		return true
	}

	return false
}

// SetPlatformMerchantAccountId gets a reference to the given string and assigns it to the PlatformMerchantAccountId field.
func (o *MerchantAccountCreateRequest) SetPlatformMerchantAccountId(v string) {
	o.PlatformMerchantAccountId = &v
}

// GetDoingBusinessAs returns the DoingBusinessAs field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetDoingBusinessAs() string {
	if o == nil || IsNil(o.DoingBusinessAs) {
		var ret string
		return ret
	}
	return *o.DoingBusinessAs
}

// GetDoingBusinessAsOk returns a tuple with the DoingBusinessAs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetDoingBusinessAsOk() (*string, bool) {
	if o == nil || IsNil(o.DoingBusinessAs) {
		return nil, false
	}
	return o.DoingBusinessAs, true
}

// HasDoingBusinessAs returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasDoingBusinessAs() bool {
	if o != nil && !IsNil(o.DoingBusinessAs) {
		return true
	}

	return false
}

// SetDoingBusinessAs gets a reference to the given string and assigns it to the DoingBusinessAs field.
func (o *MerchantAccountCreateRequest) SetDoingBusinessAs(v string) {
	o.DoingBusinessAs = &v
}

// GetBusinessPhone returns the BusinessPhone field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetBusinessPhone() string {
	if o == nil || IsNil(o.BusinessPhone) {
		var ret string
		return ret
	}
	return *o.BusinessPhone
}

// GetBusinessPhoneOk returns a tuple with the BusinessPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetBusinessPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessPhone) {
		return nil, false
	}
	return o.BusinessPhone, true
}

// HasBusinessPhone returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasBusinessPhone() bool {
	if o != nil && !IsNil(o.BusinessPhone) {
		return true
	}

	return false
}

// SetBusinessPhone gets a reference to the given string and assigns it to the BusinessPhone field.
func (o *MerchantAccountCreateRequest) SetBusinessPhone(v string) {
	o.BusinessPhone = &v
}

// GetBusinessTaxId returns the BusinessTaxId field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetBusinessTaxId() string {
	if o == nil || IsNil(o.BusinessTaxId) {
		var ret string
		return ret
	}
	return *o.BusinessTaxId
}

// GetBusinessTaxIdOk returns a tuple with the BusinessTaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetBusinessTaxIdOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessTaxId) {
		return nil, false
	}
	return o.BusinessTaxId, true
}

// HasBusinessTaxId returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasBusinessTaxId() bool {
	if o != nil && !IsNil(o.BusinessTaxId) {
		return true
	}

	return false
}

// SetBusinessTaxId gets a reference to the given string and assigns it to the BusinessTaxId field.
func (o *MerchantAccountCreateRequest) SetBusinessTaxId(v string) {
	o.BusinessTaxId = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *MerchantAccountCreateRequest) SetPhone(v string) {
	o.Phone = &v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetTaxId() string {
	if o == nil || IsNil(o.TaxId) {
		var ret string
		return ret
	}
	return *o.TaxId
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetTaxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaxId) {
		return nil, false
	}
	return o.TaxId, true
}

// HasTaxId returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasTaxId() bool {
	if o != nil && !IsNil(o.TaxId) {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given string and assigns it to the TaxId field.
func (o *MerchantAccountCreateRequest) SetTaxId(v string) {
	o.TaxId = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *MerchantAccountCreateRequest) SetEmail(v string) {
	o.Email = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *MerchantAccountCreateRequest) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *MerchantAccountCreateRequest) SetLastName(v string) {
	o.LastName = &v
}

// GetMcc returns the Mcc field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetMcc() string {
	if o == nil || IsNil(o.Mcc) {
		var ret string
		return ret
	}
	return *o.Mcc
}

// GetMccOk returns a tuple with the Mcc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetMccOk() (*string, bool) {
	if o == nil || IsNil(o.Mcc) {
		return nil, false
	}
	return o.Mcc, true
}

// HasMcc returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasMcc() bool {
	if o != nil && !IsNil(o.Mcc) {
		return true
	}

	return false
}

// SetMcc gets a reference to the given string and assigns it to the Mcc field.
func (o *MerchantAccountCreateRequest) SetMcc(v string) {
	o.Mcc = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *MerchantAccountCreateRequest) SetUrl(v string) {
	o.Url = &v
}

// GetMaxTransactionAmount returns the MaxTransactionAmount field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetMaxTransactionAmount() float32 {
	if o == nil || IsNil(o.MaxTransactionAmount) {
		var ret float32
		return ret
	}
	return *o.MaxTransactionAmount
}

// GetMaxTransactionAmountOk returns a tuple with the MaxTransactionAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetMaxTransactionAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxTransactionAmount) {
		return nil, false
	}
	return o.MaxTransactionAmount, true
}

// HasMaxTransactionAmount returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasMaxTransactionAmount() bool {
	if o != nil && !IsNil(o.MaxTransactionAmount) {
		return true
	}

	return false
}

// SetMaxTransactionAmount gets a reference to the given float32 and assigns it to the MaxTransactionAmount field.
func (o *MerchantAccountCreateRequest) SetMaxTransactionAmount(v float32) {
	o.MaxTransactionAmount = &v
}

// GetAchMaxTransactionAmount returns the AchMaxTransactionAmount field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetAchMaxTransactionAmount() float32 {
	if o == nil || IsNil(o.AchMaxTransactionAmount) {
		var ret float32
		return ret
	}
	return *o.AchMaxTransactionAmount
}

// GetAchMaxTransactionAmountOk returns a tuple with the AchMaxTransactionAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetAchMaxTransactionAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.AchMaxTransactionAmount) {
		return nil, false
	}
	return o.AchMaxTransactionAmount, true
}

// HasAchMaxTransactionAmount returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasAchMaxTransactionAmount() bool {
	if o != nil && !IsNil(o.AchMaxTransactionAmount) {
		return true
	}

	return false
}

// SetAchMaxTransactionAmount gets a reference to the given float32 and assigns it to the AchMaxTransactionAmount field.
func (o *MerchantAccountCreateRequest) SetAchMaxTransactionAmount(v float32) {
	o.AchMaxTransactionAmount = &v
}

// GetAnnualCardVolume returns the AnnualCardVolume field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetAnnualCardVolume() float32 {
	if o == nil || IsNil(o.AnnualCardVolume) {
		var ret float32
		return ret
	}
	return *o.AnnualCardVolume
}

// GetAnnualCardVolumeOk returns a tuple with the AnnualCardVolume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetAnnualCardVolumeOk() (*float32, bool) {
	if o == nil || IsNil(o.AnnualCardVolume) {
		return nil, false
	}
	return o.AnnualCardVolume, true
}

// HasAnnualCardVolume returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasAnnualCardVolume() bool {
	if o != nil && !IsNil(o.AnnualCardVolume) {
		return true
	}

	return false
}

// SetAnnualCardVolume gets a reference to the given float32 and assigns it to the AnnualCardVolume field.
func (o *MerchantAccountCreateRequest) SetAnnualCardVolume(v float32) {
	o.AnnualCardVolume = &v
}

// GetPrincipalPercentageOwnership returns the PrincipalPercentageOwnership field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetPrincipalPercentageOwnership() float32 {
	if o == nil || IsNil(o.PrincipalPercentageOwnership) {
		var ret float32
		return ret
	}
	return *o.PrincipalPercentageOwnership
}

// GetPrincipalPercentageOwnershipOk returns a tuple with the PrincipalPercentageOwnership field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetPrincipalPercentageOwnershipOk() (*float32, bool) {
	if o == nil || IsNil(o.PrincipalPercentageOwnership) {
		return nil, false
	}
	return o.PrincipalPercentageOwnership, true
}

// HasPrincipalPercentageOwnership returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasPrincipalPercentageOwnership() bool {
	if o != nil && !IsNil(o.PrincipalPercentageOwnership) {
		return true
	}

	return false
}

// SetPrincipalPercentageOwnership gets a reference to the given float32 and assigns it to the PrincipalPercentageOwnership field.
func (o *MerchantAccountCreateRequest) SetPrincipalPercentageOwnership(v float32) {
	o.PrincipalPercentageOwnership = &v
}

// GetHasAcceptedCreditCardsPreviously returns the HasAcceptedCreditCardsPreviously field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetHasAcceptedCreditCardsPreviously() bool {
	if o == nil || IsNil(o.HasAcceptedCreditCardsPreviously) {
		var ret bool
		return ret
	}
	return *o.HasAcceptedCreditCardsPreviously
}

// GetHasAcceptedCreditCardsPreviouslyOk returns a tuple with the HasAcceptedCreditCardsPreviously field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetHasAcceptedCreditCardsPreviouslyOk() (*bool, bool) {
	if o == nil || IsNil(o.HasAcceptedCreditCardsPreviously) {
		return nil, false
	}
	return o.HasAcceptedCreditCardsPreviously, true
}

// HasHasAcceptedCreditCardsPreviously returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasHasAcceptedCreditCardsPreviously() bool {
	if o != nil && !IsNil(o.HasAcceptedCreditCardsPreviously) {
		return true
	}

	return false
}

// SetHasAcceptedCreditCardsPreviously gets a reference to the given bool and assigns it to the HasAcceptedCreditCardsPreviously field.
func (o *MerchantAccountCreateRequest) SetHasAcceptedCreditCardsPreviously(v bool) {
	o.HasAcceptedCreditCardsPreviously = &v
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetDateOfBirth() MerchantProfileDate {
	if o == nil || IsNil(o.DateOfBirth) {
		var ret MerchantProfileDate
		return ret
	}
	return *o.DateOfBirth
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetDateOfBirthOk() (*MerchantProfileDate, bool) {
	if o == nil || IsNil(o.DateOfBirth) {
		return nil, false
	}
	return o.DateOfBirth, true
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasDateOfBirth() bool {
	if o != nil && !IsNil(o.DateOfBirth) {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given MerchantProfileDate and assigns it to the DateOfBirth field.
func (o *MerchantAccountCreateRequest) SetDateOfBirth(v MerchantProfileDate) {
	o.DateOfBirth = &v
}

// GetIncorporationDate returns the IncorporationDate field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetIncorporationDate() MerchantProfileDate {
	if o == nil || IsNil(o.IncorporationDate) {
		var ret MerchantProfileDate
		return ret
	}
	return *o.IncorporationDate
}

// GetIncorporationDateOk returns a tuple with the IncorporationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetIncorporationDateOk() (*MerchantProfileDate, bool) {
	if o == nil || IsNil(o.IncorporationDate) {
		return nil, false
	}
	return o.IncorporationDate, true
}

// HasIncorporationDate returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasIncorporationDate() bool {
	if o != nil && !IsNil(o.IncorporationDate) {
		return true
	}

	return false
}

// SetIncorporationDate gets a reference to the given MerchantProfileDate and assigns it to the IncorporationDate field.
func (o *MerchantAccountCreateRequest) SetIncorporationDate(v MerchantProfileDate) {
	o.IncorporationDate = &v
}

// GetBusinessAddress returns the BusinessAddress field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetBusinessAddress() MerchantAddress {
	if o == nil || IsNil(o.BusinessAddress) {
		var ret MerchantAddress
		return ret
	}
	return *o.BusinessAddress
}

// GetBusinessAddressOk returns a tuple with the BusinessAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetBusinessAddressOk() (*MerchantAddress, bool) {
	if o == nil || IsNil(o.BusinessAddress) {
		return nil, false
	}
	return o.BusinessAddress, true
}

// HasBusinessAddress returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasBusinessAddress() bool {
	if o != nil && !IsNil(o.BusinessAddress) {
		return true
	}

	return false
}

// SetBusinessAddress gets a reference to the given MerchantAddress and assigns it to the BusinessAddress field.
func (o *MerchantAccountCreateRequest) SetBusinessAddress(v MerchantAddress) {
	o.BusinessAddress = &v
}

// GetPersonalAddress returns the PersonalAddress field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetPersonalAddress() MerchantAddress {
	if o == nil || IsNil(o.PersonalAddress) {
		var ret MerchantAddress
		return ret
	}
	return *o.PersonalAddress
}

// GetPersonalAddressOk returns a tuple with the PersonalAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetPersonalAddressOk() (*MerchantAddress, bool) {
	if o == nil || IsNil(o.PersonalAddress) {
		return nil, false
	}
	return o.PersonalAddress, true
}

// HasPersonalAddress returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasPersonalAddress() bool {
	if o != nil && !IsNil(o.PersonalAddress) {
		return true
	}

	return false
}

// SetPersonalAddress gets a reference to the given MerchantAddress and assigns it to the PersonalAddress field.
func (o *MerchantAccountCreateRequest) SetPersonalAddress(v MerchantAddress) {
	o.PersonalAddress = &v
}

// GetSettlementBankAccount returns the SettlementBankAccount field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetSettlementBankAccount() MerchantSettlementBankAccount {
	if o == nil || IsNil(o.SettlementBankAccount) {
		var ret MerchantSettlementBankAccount
		return ret
	}
	return *o.SettlementBankAccount
}

// GetSettlementBankAccountOk returns a tuple with the SettlementBankAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetSettlementBankAccountOk() (*MerchantSettlementBankAccount, bool) {
	if o == nil || IsNil(o.SettlementBankAccount) {
		return nil, false
	}
	return o.SettlementBankAccount, true
}

// HasSettlementBankAccount returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasSettlementBankAccount() bool {
	if o != nil && !IsNil(o.SettlementBankAccount) {
		return true
	}

	return false
}

// SetSettlementBankAccount gets a reference to the given MerchantSettlementBankAccount and assigns it to the SettlementBankAccount field.
func (o *MerchantAccountCreateRequest) SetSettlementBankAccount(v MerchantSettlementBankAccount) {
	o.SettlementBankAccount = &v
}

// GetAssociatedIdentities returns the AssociatedIdentities field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetAssociatedIdentities() []MerchantAssociatedIdentity {
	if o == nil || IsNil(o.AssociatedIdentities) {
		var ret []MerchantAssociatedIdentity
		return ret
	}
	return o.AssociatedIdentities
}

// GetAssociatedIdentitiesOk returns a tuple with the AssociatedIdentities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetAssociatedIdentitiesOk() ([]MerchantAssociatedIdentity, bool) {
	if o == nil || IsNil(o.AssociatedIdentities) {
		return nil, false
	}
	return o.AssociatedIdentities, true
}

// HasAssociatedIdentities returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasAssociatedIdentities() bool {
	if o != nil && !IsNil(o.AssociatedIdentities) {
		return true
	}

	return false
}

// SetAssociatedIdentities gets a reference to the given []MerchantAssociatedIdentity and assigns it to the AssociatedIdentities field.
func (o *MerchantAccountCreateRequest) SetAssociatedIdentities(v []MerchantAssociatedIdentity) {
	o.AssociatedIdentities = v
}

// GetUnderwriting returns the Underwriting field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetUnderwriting() MerchantUnderwritingData {
	if o == nil || IsNil(o.Underwriting) {
		var ret MerchantUnderwritingData
		return ret
	}
	return *o.Underwriting
}

// GetUnderwritingOk returns a tuple with the Underwriting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetUnderwritingOk() (*MerchantUnderwritingData, bool) {
	if o == nil || IsNil(o.Underwriting) {
		return nil, false
	}
	return o.Underwriting, true
}

// HasUnderwriting returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasUnderwriting() bool {
	if o != nil && !IsNil(o.Underwriting) {
		return true
	}

	return false
}

// SetUnderwriting gets a reference to the given MerchantUnderwritingData and assigns it to the Underwriting field.
func (o *MerchantAccountCreateRequest) SetUnderwriting(v MerchantUnderwritingData) {
	o.Underwriting = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *MerchantAccountCreateRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAccountCreateRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *MerchantAccountCreateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *MerchantAccountCreateRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o MerchantAccountCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantAccountCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environment"] = o.Environment
	if !IsNil(o.ExternalMerchantRef) {
		toSerialize["externalMerchantRef"] = o.ExternalMerchantRef
	}
	toSerialize["displayName"] = o.DisplayName
	toSerialize["legalEntityType"] = o.LegalEntityType
	toSerialize["country"] = o.Country
	toSerialize["merchantMode"] = o.MerchantMode
	toSerialize["defaultCurrency"] = o.DefaultCurrency
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.PlatformMerchantAccountId) {
		toSerialize["platformMerchantAccountId"] = o.PlatformMerchantAccountId
	}
	if !IsNil(o.DoingBusinessAs) {
		toSerialize["doingBusinessAs"] = o.DoingBusinessAs
	}
	if !IsNil(o.BusinessPhone) {
		toSerialize["businessPhone"] = o.BusinessPhone
	}
	if !IsNil(o.BusinessTaxId) {
		toSerialize["businessTaxId"] = o.BusinessTaxId
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.TaxId) {
		toSerialize["taxId"] = o.TaxId
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.Mcc) {
		toSerialize["mcc"] = o.Mcc
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.MaxTransactionAmount) {
		toSerialize["maxTransactionAmount"] = o.MaxTransactionAmount
	}
	if !IsNil(o.AchMaxTransactionAmount) {
		toSerialize["achMaxTransactionAmount"] = o.AchMaxTransactionAmount
	}
	if !IsNil(o.AnnualCardVolume) {
		toSerialize["annualCardVolume"] = o.AnnualCardVolume
	}
	if !IsNil(o.PrincipalPercentageOwnership) {
		toSerialize["principalPercentageOwnership"] = o.PrincipalPercentageOwnership
	}
	if !IsNil(o.HasAcceptedCreditCardsPreviously) {
		toSerialize["hasAcceptedCreditCardsPreviously"] = o.HasAcceptedCreditCardsPreviously
	}
	if !IsNil(o.DateOfBirth) {
		toSerialize["dateOfBirth"] = o.DateOfBirth
	}
	if !IsNil(o.IncorporationDate) {
		toSerialize["incorporationDate"] = o.IncorporationDate
	}
	if !IsNil(o.BusinessAddress) {
		toSerialize["businessAddress"] = o.BusinessAddress
	}
	if !IsNil(o.PersonalAddress) {
		toSerialize["personalAddress"] = o.PersonalAddress
	}
	if !IsNil(o.SettlementBankAccount) {
		toSerialize["settlementBankAccount"] = o.SettlementBankAccount
	}
	if !IsNil(o.AssociatedIdentities) {
		toSerialize["associatedIdentities"] = o.AssociatedIdentities
	}
	if !IsNil(o.Underwriting) {
		toSerialize["underwriting"] = o.Underwriting
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *MerchantAccountCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environment",
		"displayName",
		"legalEntityType",
		"country",
		"merchantMode",
		"defaultCurrency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerchantAccountCreateRequest := _MerchantAccountCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMerchantAccountCreateRequest)

	if err != nil {
		return err
	}

	*o = MerchantAccountCreateRequest(varMerchantAccountCreateRequest)

	return err
}

type NullableMerchantAccountCreateRequest struct {
	value *MerchantAccountCreateRequest
	isSet bool
}

func (v NullableMerchantAccountCreateRequest) Get() *MerchantAccountCreateRequest {
	return v.value
}

func (v *NullableMerchantAccountCreateRequest) Set(val *MerchantAccountCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantAccountCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantAccountCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantAccountCreateRequest(val *MerchantAccountCreateRequest) *NullableMerchantAccountCreateRequest {
	return &NullableMerchantAccountCreateRequest{value: val, isSet: true}
}

func (v NullableMerchantAccountCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantAccountCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
