/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomerEnsureRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerEnsureRequest{}

// CustomerEnsureRequest Ensure-upsert: at least one dedupe key (externalCustomerRef or customerId) is required; resolves externalCustomerRef first.
type CustomerEnsureRequest struct {
	Name string
	DefaultCurrency string
	CustomerId *string
	ExternalCustomerRef *string
	Email *string
	Metadata map[string]string
}

type _CustomerEnsureRequest CustomerEnsureRequest

// NewCustomerEnsureRequest instantiates a new CustomerEnsureRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerEnsureRequest(name string, defaultCurrency string) *CustomerEnsureRequest {
	this := CustomerEnsureRequest{}
	return &this
}

// NewCustomerEnsureRequestWithDefaults instantiates a new CustomerEnsureRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerEnsureRequestWithDefaults() *CustomerEnsureRequest {
	this := CustomerEnsureRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CustomerEnsureRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CustomerEnsureRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CustomerEnsureRequest) SetName(v string) {
	o.Name = v
}

// GetDefaultCurrency returns the DefaultCurrency field value
func (o *CustomerEnsureRequest) GetDefaultCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultCurrency
}

// GetDefaultCurrencyOk returns a tuple with the DefaultCurrency field value
// and a boolean to check if the value has been set.
func (o *CustomerEnsureRequest) GetDefaultCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultCurrency, true
}

// SetDefaultCurrency sets field value
func (o *CustomerEnsureRequest) SetDefaultCurrency(v string) {
	o.DefaultCurrency = v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *CustomerEnsureRequest) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerEnsureRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CustomerEnsureRequest) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *CustomerEnsureRequest) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetExternalCustomerRef returns the ExternalCustomerRef field value if set, zero value otherwise.
func (o *CustomerEnsureRequest) GetExternalCustomerRef() string {
	if o == nil || IsNil(o.ExternalCustomerRef) {
		var ret string
		return ret
	}
	return *o.ExternalCustomerRef
}

// GetExternalCustomerRefOk returns a tuple with the ExternalCustomerRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerEnsureRequest) GetExternalCustomerRefOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalCustomerRef) {
		return nil, false
	}
	return o.ExternalCustomerRef, true
}

// HasExternalCustomerRef returns a boolean if a field has been set.
func (o *CustomerEnsureRequest) HasExternalCustomerRef() bool {
	if o != nil && !IsNil(o.ExternalCustomerRef) {
		return true
	}

	return false
}

// SetExternalCustomerRef gets a reference to the given string and assigns it to the ExternalCustomerRef field.
func (o *CustomerEnsureRequest) SetExternalCustomerRef(v string) {
	o.ExternalCustomerRef = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CustomerEnsureRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerEnsureRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CustomerEnsureRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CustomerEnsureRequest) SetEmail(v string) {
	o.Email = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CustomerEnsureRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerEnsureRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CustomerEnsureRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *CustomerEnsureRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o CustomerEnsureRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerEnsureRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["defaultCurrency"] = o.DefaultCurrency
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.ExternalCustomerRef) {
		toSerialize["externalCustomerRef"] = o.ExternalCustomerRef
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *CustomerEnsureRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"defaultCurrency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerEnsureRequest := _CustomerEnsureRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomerEnsureRequest)

	if err != nil {
		return err
	}

	*o = CustomerEnsureRequest(varCustomerEnsureRequest)

	return err
}

type NullableCustomerEnsureRequest struct {
	value *CustomerEnsureRequest
	isSet bool
}

func (v NullableCustomerEnsureRequest) Get() *CustomerEnsureRequest {
	return v.value
}

func (v *NullableCustomerEnsureRequest) Set(val *CustomerEnsureRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerEnsureRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerEnsureRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerEnsureRequest(val *CustomerEnsureRequest) *NullableCustomerEnsureRequest {
	return &NullableCustomerEnsureRequest{value: val, isSet: true}
}

func (v NullableCustomerEnsureRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerEnsureRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
