/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookEndpointCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEndpointCreateRequest{}

// WebhookEndpointCreateRequest struct for WebhookEndpointCreateRequest
type WebhookEndpointCreateRequest struct {
	Url string `json:"url"`
	Description *string `json:"description,omitempty"`
	EventTypes []string `json:"eventTypes"`
	// Delivery scope. Omit for the ordinary per-merchant scope (events owned by this merchant account). `platform` is only valid on an operator-activated platform account and receives events owned by its linked sub-merchants.
	Scope *string `json:"scope,omitempty"`
}

type _WebhookEndpointCreateRequest WebhookEndpointCreateRequest

// NewWebhookEndpointCreateRequest instantiates a new WebhookEndpointCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEndpointCreateRequest(url string, eventTypes []string) *WebhookEndpointCreateRequest {
	this := WebhookEndpointCreateRequest{}
	this.Url = url
	this.EventTypes = eventTypes
	return &this
}

// NewWebhookEndpointCreateRequestWithDefaults instantiates a new WebhookEndpointCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEndpointCreateRequestWithDefaults() *WebhookEndpointCreateRequest {
	this := WebhookEndpointCreateRequest{}
	return &this
}

// GetUrl returns the Url field value
func (o *WebhookEndpointCreateRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreateRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookEndpointCreateRequest) SetUrl(v string) {
	o.Url = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WebhookEndpointCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WebhookEndpointCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *WebhookEndpointCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetEventTypes returns the EventTypes field value
func (o *WebhookEndpointCreateRequest) GetEventTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.EventTypes
}

// GetEventTypesOk returns a tuple with the EventTypes field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreateRequest) GetEventTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventTypes, true
}

// SetEventTypes sets field value
func (o *WebhookEndpointCreateRequest) SetEventTypes(v []string) {
	o.EventTypes = v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *WebhookEndpointCreateRequest) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreateRequest) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *WebhookEndpointCreateRequest) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *WebhookEndpointCreateRequest) SetScope(v string) {
	o.Scope = &v
}

func (o WebhookEndpointCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEndpointCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["eventTypes"] = o.EventTypes
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	return toSerialize, nil
}

func (o *WebhookEndpointCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"eventTypes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookEndpointCreateRequest := _WebhookEndpointCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookEndpointCreateRequest)

	if err != nil {
		return err
	}

	*o = WebhookEndpointCreateRequest(varWebhookEndpointCreateRequest)

	return err
}

type NullableWebhookEndpointCreateRequest struct {
	value *WebhookEndpointCreateRequest
	isSet bool
}

func (v NullableWebhookEndpointCreateRequest) Get() *WebhookEndpointCreateRequest {
	return v.value
}

func (v *NullableWebhookEndpointCreateRequest) Set(val *WebhookEndpointCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEndpointCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEndpointCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEndpointCreateRequest(val *WebhookEndpointCreateRequest) *NullableWebhookEndpointCreateRequest {
	return &NullableWebhookEndpointCreateRequest{value: val, isSet: true}
}

func (v NullableWebhookEndpointCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEndpointCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
